# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest]
        dotnet-version: [2.1.805, 3.1.100]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.runs-on }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    
    - name: Install dependencies on ${{ matrix.dotnet-version }}
      run: dotnet restore
    
    - name: Build version ${{ matrix.dotnet-version }} on ${{ matrix.runs-on }}
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
